spring:
  application:
    name: kafka-core-consumer
  main:
    banner-mode: off
    log-startup-info: false
  jackson:
    date-format: yyyy-MM-dd
  kafka:
    listener:
      ack-mode: record
    consumer:
      group-id: kafka-core-consumer-group
      auto-offset-reset: earliest
    properties:
      metrics:
        num:
          samples: 4
